##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://evanwill.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /cb-gh-postcards
# location of code, the full url to your github repository
source-code: https://github.com/evanwill/cb-gh-postcards

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Postcards Collections
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: demo of two sided postcard objects
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "CollectionBuilder-GH is a template for creating small digital collection exhibits on GitHub Pages designed for teaching digital library skills"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: CollectionBuilder

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: postcards_demo 

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
